Solves error while testing train.
The added clip-grad feature required sending one more argument to the train function. This commits solves
"TypeError: train() missing 1 required positional argument: 'clip_grad'" in test_train.py file